// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "calculator.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



::CORBA::Exception::insertExceptionToAny calc::Calculator::DivideZeroException::insertToAnyFn = 0;
::CORBA::Exception::insertExceptionToAnyNCP calc::Calculator::DivideZeroException::insertToAnyFnNCP = 0;

calc::Calculator::DivideZeroException::DivideZeroException(const calc::Calculator::DivideZeroException& _s) : ::CORBA::UserException(_s)
{
  reason = _s.reason;

}

calc::Calculator::DivideZeroException::DivideZeroException(const char* _reason)
{
  pd_insertToAnyFn    = calc::Calculator::DivideZeroException::insertToAnyFn;
  pd_insertToAnyFnNCP = calc::Calculator::DivideZeroException::insertToAnyFnNCP;
  reason = _reason;

}



calc::Calculator::DivideZeroException& calc::Calculator::DivideZeroException::operator=(const calc::Calculator::DivideZeroException& _s)
{
  if (&_s != this) {
    ((::CORBA::UserException*) this)->operator=(_s);
    reason = _s.reason;

  }
  return *this;
}

calc::Calculator::DivideZeroException::~DivideZeroException() {}

void calc::Calculator::DivideZeroException::_raise() const { throw *this; }

const char* calc::Calculator::DivideZeroException::_PD_repoId = "IDL:calc/Calculator/DivideZeroException:1.0";
const char* calc::Calculator::DivideZeroException::_PD_typeId = "Exception/UserException/calc::Calculator::DivideZeroException";

calc::Calculator::DivideZeroException* calc::Calculator::DivideZeroException::_downcast(::CORBA::Exception* _e) {
  return (DivideZeroException*) _NP_is_a(_e, _PD_typeId);
}

const calc::Calculator::DivideZeroException* calc::Calculator::DivideZeroException::_downcast(const ::CORBA::Exception* _e) {
  return (const DivideZeroException*) _NP_is_a(_e, _PD_typeId);
}

::CORBA::Exception* calc::Calculator::DivideZeroException::_NP_duplicate() const {
  return new DivideZeroException(*this);
}

const char* calc::Calculator::DivideZeroException::_NP_typeId() const {
  return _PD_typeId;
}

const char* calc::Calculator::DivideZeroException::_NP_repoId(int* _size) const {
  *_size = sizeof("IDL:calc/Calculator/DivideZeroException:1.0");
  return _PD_repoId;
}
 
void calc::Calculator::DivideZeroException::_NP_marshal(cdrStream& _s) const {
  *this >>= _s;
}

void
calc::Calculator::DivideZeroException::operator>>= (cdrStream& _n) const
{
  _n.marshalString(reason,0);

}

void
calc::Calculator::DivideZeroException::operator<<= (cdrStream& _n)
{
  reason = _n.unmarshalString(0);

}

calc::Calculator_ptr calc::Calculator_Helper::_nil() {
  return ::calc::Calculator::_nil();
}

::CORBA::Boolean calc::Calculator_Helper::is_nil(::calc::Calculator_ptr p) {
  return ::CORBA::is_nil(p);

}

void calc::Calculator_Helper::release(::calc::Calculator_ptr p) {
  ::CORBA::release(p);
}

void calc::Calculator_Helper::marshalObjRef(::calc::Calculator_ptr obj, cdrStream& s) {
  ::calc::Calculator::_marshalObjRef(obj, s);
}

calc::Calculator_ptr calc::Calculator_Helper::unmarshalObjRef(cdrStream& s) {
  return ::calc::Calculator::_unmarshalObjRef(s);
}

void calc::Calculator_Helper::duplicate(::calc::Calculator_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

calc::Calculator_ptr
calc::Calculator::_duplicate(::calc::Calculator_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

calc::Calculator_ptr
calc::Calculator::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


calc::Calculator_ptr
calc::Calculator::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

calc::Calculator_ptr
calc::Calculator::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_Calculator _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_Calculator* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_Calculator;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* calc::Calculator::_PD_repoId = "IDL:calc/Calculator:1.0";


calc::_objref_Calculator::~_objref_Calculator() {
  
}


calc::_objref_Calculator::_objref_Calculator(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::calc::Calculator::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
calc::_objref_Calculator::_ptrToObjRef(const char* id)
{
  if (id == ::calc::Calculator::_PD_repoId)
    return (::calc::Calculator_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::calc::Calculator::_PD_repoId))
    return (::calc::Calculator_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for calc::Calculator::mul

// Proxy call descriptor class. Mangled signature:
//  _clong_i_clong_i_clong
class _0RL_cd_a94663051ab3173f_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a94663051ab3173f_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_a94663051ab3173f_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_a94663051ab3173f_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

void _0RL_cd_a94663051ab3173f_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a94663051ab3173f_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_a94663051ab3173f_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a94663051ab3173f_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a94663051ab3173f_00000000* tcd = (_0RL_cd_a94663051ab3173f_00000000*)cd;
  calc::_impl_Calculator* impl = (calc::_impl_Calculator*) svnt->_ptrToInterface(calc::Calculator::_PD_repoId);
  tcd->result = impl->mul(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long calc::_objref_Calculator::mul(::CORBA::Long a, ::CORBA::Long b)
{
  _0RL_cd_a94663051ab3173f_00000000 _call_desc(_0RL_lcfn_a94663051ab3173f_10000000, "mul", 4);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for calc::Calculator::sub

// Local call call-back function.
static void
_0RL_lcfn_a94663051ab3173f_20000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a94663051ab3173f_00000000* tcd = (_0RL_cd_a94663051ab3173f_00000000*)cd;
  calc::_impl_Calculator* impl = (calc::_impl_Calculator*) svnt->_ptrToInterface(calc::Calculator::_PD_repoId);
  tcd->result = impl->sub(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long calc::_objref_Calculator::sub(::CORBA::Long a, ::CORBA::Long b)
{
  _0RL_cd_a94663051ab3173f_00000000 _call_desc(_0RL_lcfn_a94663051ab3173f_20000000, "sub", 4);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for calc::Calculator::add

// Local call call-back function.
static void
_0RL_lcfn_a94663051ab3173f_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a94663051ab3173f_00000000* tcd = (_0RL_cd_a94663051ab3173f_00000000*)cd;
  calc::_impl_Calculator* impl = (calc::_impl_Calculator*) svnt->_ptrToInterface(calc::Calculator::_PD_repoId);
  tcd->result = impl->add(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long calc::_objref_Calculator::add(::CORBA::Long a, ::CORBA::Long b)
{
  _0RL_cd_a94663051ab3173f_00000000 _call_desc(_0RL_lcfn_a94663051ab3173f_30000000, "add", 4);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}


//
// Code for calc::Calculator::div

// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_clong_i_clong_e_ccalc_mCalculator_mDivideZeroException
class _0RL_cd_a94663051ab3173f_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a94663051ab3173f_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 1, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  void userException(cdrStream&, _OMNI_NS(IOP_C)*, const char*);
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Double result;
};

void _0RL_cd_a94663051ab3173f_40000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_a94663051ab3173f_40000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

void _0RL_cd_a94663051ab3173f_40000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a94663051ab3173f_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_a94663051ab3173f_40000000::_user_exns[] = {
  calc::Calculator::DivideZeroException::_PD_repoId
};

void _0RL_cd_a94663051ab3173f_40000000::userException(cdrStream& s, _OMNI_NS(IOP_C)* iop_client, const char* repoId)
{
  if (omni::strMatch(repoId, calc::Calculator::DivideZeroException::_PD_repoId)) {
    calc::Calculator::DivideZeroException _ex;
    _ex <<= s;
    if (iop_client) iop_client->RequestCompleted();
    throw _ex;
  }


  else {
    if (iop_client) iop_client->RequestCompleted(1);
    OMNIORB_THROW(UNKNOWN,UNKNOWN_UserException,
                  (::CORBA::CompletionStatus)s.completion());
  }
}

// Local call call-back function.
static void
_0RL_lcfn_a94663051ab3173f_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a94663051ab3173f_40000000* tcd = (_0RL_cd_a94663051ab3173f_40000000*)cd;
  calc::_impl_Calculator* impl = (calc::_impl_Calculator*) svnt->_ptrToInterface(calc::Calculator::_PD_repoId);
#ifdef HAS_Cplusplus_catch_exception_by_base
  tcd->result = impl->div(tcd->arg_0, tcd->arg_1);
#else
  if (!cd->is_upcall())
    tcd->result = impl->div(tcd->arg_0, tcd->arg_1);
  else {
    try {
      tcd->result = impl->div(tcd->arg_0, tcd->arg_1);
    }
    catch(calc::Calculator::DivideZeroException& ex) {
      throw omniORB::StubUserException(ex._NP_duplicate());
    }


  }
#endif


}

::CORBA::Double calc::_objref_Calculator::div(::CORBA::Long a, ::CORBA::Long b)
{
  _0RL_cd_a94663051ab3173f_40000000 _call_desc(_0RL_lcfn_a94663051ab3173f_50000000, "div", 4);
  _call_desc.arg_0 = a;
  _call_desc.arg_1 = b;

  _invoke(_call_desc);
  return _call_desc.result;


}

calc::_pof_Calculator::~_pof_Calculator() {}


omniObjRef*
calc::_pof_Calculator::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::calc::_objref_Calculator(ior, id);
}


::CORBA::Boolean
calc::_pof_Calculator::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::calc::Calculator::_PD_repoId))
    return 1;
  
  return 0;
}

const calc::_pof_Calculator _the_pof_calc_mCalculator;

calc::_impl_Calculator::~_impl_Calculator() {}


::CORBA::Boolean
calc::_impl_Calculator::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "mul")) {

    _0RL_cd_a94663051ab3173f_00000000 _call_desc(_0RL_lcfn_a94663051ab3173f_10000000, "mul", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "sub")) {

    _0RL_cd_a94663051ab3173f_00000000 _call_desc(_0RL_lcfn_a94663051ab3173f_20000000, "sub", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "add")) {

    _0RL_cd_a94663051ab3173f_00000000 _call_desc(_0RL_lcfn_a94663051ab3173f_30000000, "add", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "div")) {

    _0RL_cd_a94663051ab3173f_40000000 _call_desc(_0RL_lcfn_a94663051ab3173f_50000000, "div", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
calc::_impl_Calculator::_ptrToInterface(const char* id)
{
  if (id == ::calc::Calculator::_PD_repoId)
    return (::calc::_impl_Calculator*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::calc::Calculator::_PD_repoId))
    return (::calc::_impl_Calculator*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
calc::_impl_Calculator::_mostDerivedRepoId()
{
  return ::calc::Calculator::_PD_repoId;
}

POA_calc::Calculator::~Calculator() {}

