// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __echo_hh__
#define __echo_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_echo
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_echo
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_echo
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE cb

_CORBA_MODULE_BEG

#ifndef __cb_mCallBack__
#define __cb_mCallBack__
  class CallBack;
  class _objref_CallBack;
  class _impl_CallBack;
  
  typedef _objref_CallBack* CallBack_ptr;
  typedef CallBack_ptr CallBackRef;

  class CallBack_Helper {
  public:
    typedef CallBack_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_CallBack, CallBack_Helper> CallBack_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_CallBack,CallBack_Helper > CallBack_out;

#endif

  // interface CallBack
  class CallBack {
  public:
    // Declarations for this interface type.
    typedef CallBack_ptr _ptr_type;
    typedef CallBack_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_CallBack :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void call_back(const char* msg);

    // Constructors
    inline _objref_CallBack()  { _PR_setobj(0); }  // nil
    _objref_CallBack(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_CallBack();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_CallBack(const _objref_CallBack&);
    _objref_CallBack& operator = (const _objref_CallBack&);
    // not implemented

    friend class CallBack;
  };

  class _pof_CallBack : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_CallBack() : _OMNI_NS(proxyObjectFactory)(CallBack::_PD_repoId) {}
    virtual ~_pof_CallBack();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_CallBack :
    public virtual omniServant
  {
  public:
    virtual ~_impl_CallBack();

    virtual void call_back(const char* msg) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


#ifndef __cb_mserver__
#define __cb_mserver__
  class server;
  class _objref_server;
  class _impl_server;
  
  typedef _objref_server* server_ptr;
  typedef server_ptr serverRef;

  class server_Helper {
  public:
    typedef server_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_server, server_Helper> server_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_server,server_Helper > server_out;

#endif

  // interface server
  class server {
  public:
    // Declarations for this interface type.
    typedef server_ptr _ptr_type;
    typedef server_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_server :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void one_time(::cb::CallBack_ptr cb, const char* msg);
    void _cxx_register(::cb::CallBack_ptr cb, const char* msg, ::CORBA::UShort period_scs);
    void shutdown();

    // Constructors
    inline _objref_server()  { _PR_setobj(0); }  // nil
    _objref_server(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_server();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_server(const _objref_server&);
    _objref_server& operator = (const _objref_server&);
    // not implemented

    friend class server;
  };

  class _pof_server : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_server() : _OMNI_NS(proxyObjectFactory)(server::_PD_repoId) {}
    virtual ~_pof_server();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_server :
    public virtual omniServant
  {
  public:
    virtual ~_impl_server();

    virtual void one_time(::cb::CallBack_ptr cb, const char* msg) = 0;
    virtual void _cxx_register(::cb::CallBack_ptr cb, const char* msg, ::CORBA::UShort period_scs) = 0;
    virtual void shutdown() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_cb
_CORBA_MODULE_BEG

  class CallBack :
    public virtual cb::_impl_CallBack,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~CallBack();

    inline ::cb::CallBack_ptr _this() {
      return (::cb::CallBack_ptr) _do_this(::cb::CallBack::_PD_repoId);
    }
  };

  class server :
    public virtual cb::_impl_server,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~server();

    inline ::cb::server_ptr _this() {
      return (::cb::server_ptr) _do_this(::cb::server::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_cb
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
cb::CallBack::_marshalObjRef(::cb::CallBack_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}

inline void
cb::server::_marshalObjRef(::cb::server_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_echo
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_echo
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_echo
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_echo
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_echo
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_echo
#endif

#endif  // __echo_hh__

