// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "echo.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



cb::CallBack_ptr cb::CallBack_Helper::_nil() {
  return ::cb::CallBack::_nil();
}

::CORBA::Boolean cb::CallBack_Helper::is_nil(::cb::CallBack_ptr p) {
  return ::CORBA::is_nil(p);

}

void cb::CallBack_Helper::release(::cb::CallBack_ptr p) {
  ::CORBA::release(p);
}

void cb::CallBack_Helper::marshalObjRef(::cb::CallBack_ptr obj, cdrStream& s) {
  ::cb::CallBack::_marshalObjRef(obj, s);
}

cb::CallBack_ptr cb::CallBack_Helper::unmarshalObjRef(cdrStream& s) {
  return ::cb::CallBack::_unmarshalObjRef(s);
}

void cb::CallBack_Helper::duplicate(::cb::CallBack_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

cb::CallBack_ptr
cb::CallBack::_duplicate(::cb::CallBack_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

cb::CallBack_ptr
cb::CallBack::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


cb::CallBack_ptr
cb::CallBack::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

cb::CallBack_ptr
cb::CallBack::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_CallBack _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_CallBack* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_CallBack;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* cb::CallBack::_PD_repoId = "IDL:cb/CallBack:1.0";


cb::_objref_CallBack::~_objref_CallBack() {
  
}


cb::_objref_CallBack::_objref_CallBack(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::cb::CallBack::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
cb::_objref_CallBack::_ptrToObjRef(const char* id)
{
  if (id == ::cb::CallBack::_PD_repoId)
    return (::cb::CallBack_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::cb::CallBack::_PD_repoId))
    return (::cb::CallBack_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for cb::CallBack::call_back

// Proxy call descriptor class. Mangled signature:
//  void_i_cstring
class _0RL_cd_db735b792e25d186_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_db735b792e25d186_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
};

void _0RL_cd_db735b792e25d186_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);

}

void _0RL_cd_db735b792e25d186_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();

}

const char* const _0RL_cd_db735b792e25d186_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_db735b792e25d186_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_db735b792e25d186_00000000* tcd = (_0RL_cd_db735b792e25d186_00000000*)cd;
  cb::_impl_CallBack* impl = (cb::_impl_CallBack*) svnt->_ptrToInterface(cb::CallBack::_PD_repoId);
  impl->call_back(tcd->arg_0);


}

void cb::_objref_CallBack::call_back(const char* msg)
{
  _0RL_cd_db735b792e25d186_00000000 _call_desc(_0RL_lcfn_db735b792e25d186_10000000, "call_back", 10);
  _call_desc.arg_0 = msg;

  _invoke(_call_desc);



}

cb::_pof_CallBack::~_pof_CallBack() {}


omniObjRef*
cb::_pof_CallBack::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::cb::_objref_CallBack(ior, id);
}


::CORBA::Boolean
cb::_pof_CallBack::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::cb::CallBack::_PD_repoId))
    return 1;
  
  return 0;
}

const cb::_pof_CallBack _the_pof_cb_mCallBack;

cb::_impl_CallBack::~_impl_CallBack() {}


::CORBA::Boolean
cb::_impl_CallBack::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "call_back")) {

    _0RL_cd_db735b792e25d186_00000000 _call_desc(_0RL_lcfn_db735b792e25d186_10000000, "call_back", 10, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
cb::_impl_CallBack::_ptrToInterface(const char* id)
{
  if (id == ::cb::CallBack::_PD_repoId)
    return (::cb::_impl_CallBack*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::cb::CallBack::_PD_repoId))
    return (::cb::_impl_CallBack*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
cb::_impl_CallBack::_mostDerivedRepoId()
{
  return ::cb::CallBack::_PD_repoId;
}

cb::server_ptr cb::server_Helper::_nil() {
  return ::cb::server::_nil();
}

::CORBA::Boolean cb::server_Helper::is_nil(::cb::server_ptr p) {
  return ::CORBA::is_nil(p);

}

void cb::server_Helper::release(::cb::server_ptr p) {
  ::CORBA::release(p);
}

void cb::server_Helper::marshalObjRef(::cb::server_ptr obj, cdrStream& s) {
  ::cb::server::_marshalObjRef(obj, s);
}

cb::server_ptr cb::server_Helper::unmarshalObjRef(cdrStream& s) {
  return ::cb::server::_unmarshalObjRef(s);
}

void cb::server_Helper::duplicate(::cb::server_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

cb::server_ptr
cb::server::_duplicate(::cb::server_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

cb::server_ptr
cb::server::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


cb::server_ptr
cb::server::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

cb::server_ptr
cb::server::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_server _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_server* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_server;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* cb::server::_PD_repoId = "IDL:cb/server:1.0";


cb::_objref_server::~_objref_server() {
  
}


cb::_objref_server::_objref_server(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::cb::server::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
cb::_objref_server::_ptrToObjRef(const char* id)
{
  if (id == ::cb::server::_PD_repoId)
    return (::cb::server_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::cb::server::_PD_repoId))
    return (::cb::server_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for cb::server::one_time

// Proxy call descriptor class. Mangled signature:
//  void_i_ccb_mCallBack_i_cstring
class _0RL_cd_db735b792e25d186_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_db735b792e25d186_20000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  cb::CallBack_var arg_0_;
  cb::CallBack_ptr arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
};

void _0RL_cd_db735b792e25d186_20000000::marshalArguments(cdrStream& _n)
{
  cb::CallBack::_marshalObjRef(arg_0,_n);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_db735b792e25d186_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = cb::CallBack::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

const char* const _0RL_cd_db735b792e25d186_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_db735b792e25d186_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_db735b792e25d186_20000000* tcd = (_0RL_cd_db735b792e25d186_20000000*)cd;
  cb::_impl_server* impl = (cb::_impl_server*) svnt->_ptrToInterface(cb::server::_PD_repoId);
  impl->one_time(tcd->arg_0, tcd->arg_1);


}

void cb::_objref_server::one_time(::cb::CallBack_ptr cb, const char* msg)
{
  _0RL_cd_db735b792e25d186_20000000 _call_desc(_0RL_lcfn_db735b792e25d186_30000000, "one_time", 9);
  _call_desc.arg_0 = cb;
  _call_desc.arg_1 = msg;

  _invoke(_call_desc);



}


//
// Code for cb::server::register

// Proxy call descriptor class. Mangled signature:
//  void_i_ccb_mCallBack_i_cstring_i_cunsigned_pshort
class _0RL_cd_db735b792e25d186_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_db735b792e25d186_40000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  static const char* const _user_exns[];

  cb::CallBack_var arg_0_;
  cb::CallBack_ptr arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::UShort arg_2;
};

void _0RL_cd_db735b792e25d186_40000000::marshalArguments(cdrStream& _n)
{
  cb::CallBack::_marshalObjRef(arg_0,_n);
  _n.marshalString(arg_1,0);
  arg_2 >>= _n;

}

void _0RL_cd_db735b792e25d186_40000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = cb::CallBack::_unmarshalObjRef(_n);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  (::CORBA::UShort&)arg_2 <<= _n;

}

const char* const _0RL_cd_db735b792e25d186_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_db735b792e25d186_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_db735b792e25d186_40000000* tcd = (_0RL_cd_db735b792e25d186_40000000*)cd;
  cb::_impl_server* impl = (cb::_impl_server*) svnt->_ptrToInterface(cb::server::_PD_repoId);
  impl->_cxx_register(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

void cb::_objref_server::_cxx_register(::cb::CallBack_ptr cb, const char* msg, ::CORBA::UShort period_scs)
{
  _0RL_cd_db735b792e25d186_40000000 _call_desc(_0RL_lcfn_db735b792e25d186_50000000, "register", 9);
  _call_desc.arg_0 = cb;
  _call_desc.arg_1 = msg;
  _call_desc.arg_2 = period_scs;

  _invoke(_call_desc);



}


//
// Code for cb::server::shutdown

// Proxy call descriptor class. Mangled signature:
//  void
class _0RL_cd_db735b792e25d186_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_db735b792e25d186_60000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  
    
  
  static const char* const _user_exns[];

  
};

const char* const _0RL_cd_db735b792e25d186_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_db735b792e25d186_70000000(omniCallDescriptor*, omniServant* svnt)
{
  
  cb::_impl_server* impl = (cb::_impl_server*) svnt->_ptrToInterface(cb::server::_PD_repoId);
  impl->shutdown();


}

void cb::_objref_server::shutdown()
{
  _0RL_cd_db735b792e25d186_60000000 _call_desc(_0RL_lcfn_db735b792e25d186_70000000, "shutdown", 9);


  _invoke(_call_desc);



}

cb::_pof_server::~_pof_server() {}


omniObjRef*
cb::_pof_server::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::cb::_objref_server(ior, id);
}


::CORBA::Boolean
cb::_pof_server::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::cb::server::_PD_repoId))
    return 1;
  
  return 0;
}

const cb::_pof_server _the_pof_cb_mserver;

cb::_impl_server::~_impl_server() {}


::CORBA::Boolean
cb::_impl_server::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "one_time")) {

    _0RL_cd_db735b792e25d186_20000000 _call_desc(_0RL_lcfn_db735b792e25d186_30000000, "one_time", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "register")) {

    _0RL_cd_db735b792e25d186_40000000 _call_desc(_0RL_lcfn_db735b792e25d186_50000000, "register", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if (omni::strMatch(op, "shutdown")) {

    _0RL_cd_db735b792e25d186_60000000 _call_desc(_0RL_lcfn_db735b792e25d186_70000000, "shutdown", 9, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
cb::_impl_server::_ptrToInterface(const char* id)
{
  if (id == ::cb::server::_PD_repoId)
    return (::cb::_impl_server*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::cb::server::_PD_repoId))
    return (::cb::_impl_server*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
cb::_impl_server::_mostDerivedRepoId()
{
  return ::cb::server::_PD_repoId;
}

POA_cb::CallBack::~CallBack() {}

POA_cb::server::~server() {}

